In [1]:
import pandas as pd

# Load S&P 500 constituents
sp500 = pd.read_csv("data/sp500_list.csv")

tickers = sp500["ticker"].tolist()

print(f"Number of tickers: {len(tickers)}")

Number of tickers: 504

In [2]:
import yfinance as yf

start_date = "2010-01-01"
end_date = None  # up to today

stocks = yf.download(
    tickers,
    start=start_date,
    end=end_date,
    auto_adjust=False,
    progress=True,
    group_by="ticker"
)

[*********************100%***********************]  504 of 504 completed

In [3]:
display(stocks)

Ticker            ABNB                                                  \
Price             Open        High         Low       Close   Adj Close
Date
2010-01-04         NaN         NaN         NaN         NaN         NaN
2010-01-05         NaN         NaN         NaN         NaN         NaN
2010-01-06         NaN         NaN         NaN         NaN         NaN
2010-01-07         NaN         NaN         NaN         NaN         NaN
2010-01-08         NaN         NaN         NaN         NaN         NaN
...                ...         ...         ...         ...         ...
2026-04-13  127.199997  130.649994  125.360001  130.320007  130.320007
2026-04-14  130.500000  134.660004  130.470001  133.850006  133.850006
2026-04-15  134.509995  138.050003  134.100006  137.509995  137.509995
2026-04-16  138.869995  139.949997  136.910004  137.809998  137.809998
2026-04-17  139.904999  143.300003  139.199997  141.550003  141.550003

Ticker                        VRT                                      ...  \
Price          Volume        Open        High         Low       Close  ...
Date                                                                   ...
2010-01-04        NaN         NaN         NaN         NaN         NaN  ...
2010-01-05        NaN         NaN         NaN         NaN         NaN  ...
2010-01-06        NaN         NaN         NaN         NaN         NaN  ...
2010-01-07        NaN         NaN         NaN         NaN         NaN  ...
2010-01-08        NaN         NaN         NaN         NaN         NaN  ...
...               ...         ...         ...         ...         ...  ...
2026-04-13  3256600.0  294.980011  300.679993  294.980011  299.959991  ...
2026-04-14  3113300.0  307.000000  312.459991  299.010010  310.510010  ...
2026-04-15  3562400.0  309.500000  311.000000  296.640015  301.160004  ...
2026-04-16  2692600.0  303.000000  303.309998  292.670013  294.130005  ...
2026-04-17  4056300.0  298.700012  308.540009  298.220001  307.339996  ...

Ticker             KO                                        CCI             \
Price             Low      Close  Adj Close    Volume       Open       High
Date
2010-01-04  28.450001  28.520000  17.316328  13870400  39.410000  40.150002
2010-01-05  28.070000  28.174999  17.106861  23172400  39.759998  40.490002
2010-01-06  27.990000  28.165001  17.100790  19264600  39.529999  39.849998
2010-01-07  27.875000  28.094999  17.058287  13234600  39.450001  39.450001
2010-01-08  27.375000  27.575001  16.742559  28712400  38.779999  39.139999
...               ...        ...        ...       ...        ...        ...
2026-04-13  75.830002  76.410004  76.410004  12696200  86.230003  87.099998
2026-04-14  75.800003  75.900002  75.900002  12397600  87.050003  87.220001
2026-04-15  74.720001  75.309998  75.309998  16212100  86.480003  87.050003
2026-04-16  74.900002  75.180000  75.180000  11501900  85.790001  86.900002
2026-04-17  74.800003  75.739998  75.739998  15006900  86.959999  89.000000

Ticker
Price             Low      Close  Adj Close   Volume
Date
2010-01-04  39.330002  39.610001  24.200470  1964100
2010-01-05  39.630001  39.990002  24.432638  2116000
2010-01-06  39.119999  39.419998  24.084377  1612100
2010-01-07  38.610001  38.770000  23.687248  1671500
2010-01-08  38.299999  38.959999  23.803335  2004200
...               ...        ...        ...      ...
2026-04-13  85.720001  87.080002  87.080002  2339800
2026-04-14  85.120003  86.269997  86.269997  2775200
2026-04-15  85.449997  85.629997  85.629997  2696200
2026-04-16  85.669998  86.870003  86.870003  2534800
2026-04-17  86.440002  88.709999  88.709999  3436500

[4097 rows x 3024 columns]

In [4]:
# Ensure datetime index
stocks.index = pd.to_datetime(stocks.index)

stocks = (
    stocks
    .stack(level=0)
    .reset_index()
)


stocks.head()

/tmp/ipykernel_343841/148835718.py:6: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  .stack(level=0)

Price,Date,Ticker,Open,High,Low,Close,Adj Close,Volume
0,2010-01-04,A,22.453505,22.625179,22.267525,22.389128,19.810984,3815561.0
1,2010-01-04,AAPL,7.622500,7.660714,7.585000,7.643214,6.412382,493729600.0
2,2010-01-04,ABT,26.000362,26.177889,25.870815,26.129908,18.207748,10829095.0
3,2010-01-04,ACGL,7.978889,8.022222,7.972222,7.994444,7.601905,4813200.0
4,2010-01-04,ACN,41.520000,42.200001,41.500000,42.070000,31.227346,3650100.0

In [5]:

stocks_with_data = stocks[
    stocks["Date"] == pd.Timestamp("2010-01-04")
]

stocks_with_data = pd. unique(stocks_with_data["Ticker"])

len(stocks_with_data)

424

In [6]:
df_to_save = stocks[stocks["Ticker"].isin(stocks_with_data)]

df_to_save.to_csv("data/sp500_data_from_2010.csv", index=False)