In [1]:
import pandas as pd

# Load S&P 500 constituents
sp500 = pd.read_csv("data/sp500_list.csv")

tickers = sp500["ticker"].tolist()

print(f"Number of tickers: {len(tickers)}")

Number of tickers: 501

In [2]:
import yfinance as yf

start_date = "2010-01-01"
end_date = None  # up to today

stocks = yf.download(
    tickers,
    start=start_date,
    end=end_date,
    auto_adjust=False,
    progress=True,
    group_by="ticker"
)

[*********************100%***********************]  501 of 501 completed

In [11]:
display(prices)

Ticker            DASH                                                  \
Price             Open        High         Low       Close   Adj Close
Date
2010-01-04         NaN         NaN         NaN         NaN         NaN
2010-01-05         NaN         NaN         NaN         NaN         NaN
2010-01-06         NaN         NaN         NaN         NaN         NaN
2010-01-07         NaN         NaN         NaN         NaN         NaN
2010-01-08         NaN         NaN         NaN         NaN         NaN
...                ...         ...         ...         ...         ...
2025-12-23  233.289993  233.979996  230.100006  232.699997  232.699997
2025-12-24  231.979996  233.240005  230.570007  232.059998  232.059998
2025-12-26  232.520004  234.695007  231.759995  233.949997  233.949997
2025-12-29  233.070007  235.000000  230.089996  231.009995  231.009995
2025-12-30  230.250000  231.320007  228.720001  230.460007  230.460007

Ticker                       DAY                                   ...  \
Price          Volume       Open       High        Low      Close  ...
Date                                                               ...
2010-01-04        NaN        NaN        NaN        NaN        NaN  ...
2010-01-05        NaN        NaN        NaN        NaN        NaN  ...
2010-01-06        NaN        NaN        NaN        NaN        NaN  ...
2010-01-07        NaN        NaN        NaN        NaN        NaN  ...
2010-01-08        NaN        NaN        NaN        NaN        NaN  ...
...               ...        ...        ...        ...        ...  ...
2025-12-23  2694900.0  69.180000  69.199997  69.110001  69.139999  ...
2025-12-24  1223400.0  69.150002  69.160004  69.120003  69.139999  ...
2025-12-26  1706700.0  69.139999  69.205002  69.080002  69.160004  ...
2025-12-29  2717200.0  69.199997  69.239998  69.139999  69.220001  ...
2025-12-30    87132.0  69.199997  69.209999  69.190002  69.205002  ...

Ticker            FCX                                         PNC              \
Price             Low      Close  Adj Close    Volume        Open        High
Date
2010-01-04  41.275002  41.730000  30.001995  18082400   53.740002   54.099998
2010-01-05  41.564999  41.980000  30.181726  17313000   53.270000   54.070000
2010-01-06  42.384998  43.654999  31.385977  30691200   54.029999   54.849998
2010-01-07  42.505001  42.820000  30.785650  19499200   53.849998   57.209999
2010-01-08  42.404999  44.049999  31.669973  21313200   56.810001   57.520000
...               ...        ...        ...       ...         ...         ...
2025-12-23  50.990002  51.900002  51.900002  14155700  212.899994  213.979996
2025-12-24  51.230000  51.919998  51.919998   4073900  211.960007  214.589996
2025-12-26  52.639999  53.040001  53.040001  14848300  213.229996  214.210007
2025-12-29  51.169998  51.480000  51.480000  15224300  213.970001  214.020004
2025-12-30  51.049999  51.230000  51.230000   1624563  213.970001  212.270004

Ticker
Price              Low       Close   Adj Close   Volume
Date
2010-01-04   53.200001   53.509998   34.300400  4890300
2010-01-05   53.029999   54.049999   34.646542  6379300
2010-01-06   53.669998   54.049999   34.646542  3013600
2010-01-07   53.750000   56.980000   36.524700  5700800
2010-01-08   56.099998   57.130001   36.620861  3770800
...                ...         ...         ...      ...
2025-12-23  211.610001  211.949997  211.949997  1121900
2025-12-24  211.320007  213.479996  213.479996   712800
2025-12-26  212.580002  213.889999  213.889999   887300
2025-12-29  211.869995  211.970001  211.970001  1274600
2025-12-30  211.190002  211.580002  211.580002    26191

[4023 rows x 3006 columns]

In [3]:
# Ensure datetime index
stocks.index = pd.to_datetime(stocks.index)

stocks = (
    stocks
    .stack(level=0)
    .reset_index()
)


stocks.head()

/tmp/ipykernel_761529/148835718.py:6: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  .stack(level=0)

Price,Date,Ticker,Open,High,Low,Close,Adj Close,Volume
0,2010-01-04,A,22.453505,22.625179,22.267525,22.389128,19.891682,3815561.0
1,2010-01-04,AAPL,7.622500,7.660714,7.585000,7.643214,6.418382,493729600.0
2,2010-01-04,ABT,26.000362,26.177889,25.870815,26.129908,18.414783,10829095.0
3,2010-01-04,ACGL,7.978889,8.022222,7.972222,7.994444,7.601905,4813200.0
4,2010-01-04,ACN,41.520000,42.200001,41.500000,42.070000,31.492174,3650100.0

In [8]:

stocks_with_data = stocks[
    stocks["Date"] == pd.Timestamp("2010-01-04")
]

stocks_with_data = pd. unique(stocks_with_data["Ticker"])

len(stocks_with_data)

420

In [9]:
df_to_save = stocks[stocks["Ticker"].isin(stocks_with_data)]

df_to_save.to_csv("data/sp500_data_from_2010.csv", index=False)